"""OpenAI bot commands cog module"""
import os
import time

import discord
import openai
from discord.ext import commands
from core.basecog import BaseCog

from .chatlog import ChatLog


class OpenAI(BaseCog):
    """Bot openai commands and direct message handler cog"""

    def __init__(self, bot: commands.Bot) -> None:
        """Chat class init with empty chat log for each user.

        Loads an openai API key from config, which it uses to access Completion engine
        """
        super().__init__(bot)
        self.chats = {}
        openai.api_key = self.config.openai["key"]

    def _get_chatlog_from_user(self, user, botname) -> ChatLog:
        """Get chatlog from user id."""
        if user.id not in self.chats:
            self.chats[user.id] = ChatLog(user, botname)
        return self.chats[user.id]

    def _get_ai_response(self, author, message: str) -> str:
        """Get AI response from user_id and prompt.

        Response is generator from davinci engine using log bound to user and prompt."""
        botname = self.bot.user.name
        chatlog = str(self._get_chatlog_from_user(author, botname))
        prompt = f"{chatlog}\n{author.name}: {message}\n{botname}: "
        response = openai.Completion.create(
            prompt=prompt,
            engine="davinci",
            stop=[f"\n{author.name}", f"\n{botname}", f" {author.name}:", f" {botname}:"],
            temperature=0.8,
            top_p=1,
            frequency_penalty=0.7,
            best_of=1,
            max_tokens=150,
        )
        answer = response.choices[0].text.strip()
        self.chats[author.id].add(f"\n{author.name}: {message}\n{botname}: {answer}")
        if answer == "":
            answer = "*silence*"
        return answer

    @commands.Cog.listener()
    async def on_message(self, message) -> None:
        """Chat in Direct message by default.

        If the message is a command, it will be ignored.
        """

        if message.guild is None:
            if message.author.bot:
                return
            if message.content.lower().startswith(self.config.default_prefix):
                # Ignore commands in Direct message
                return  # Which is always default prefix from bot.py
            text_channel = message.channel

            log_user = f"{message.author.name}#{message.author.discriminator}"
            log_message = log_user + " issued `openai` in Direct message."
            self.logger.debug(log_message)
            start = time.time()

            async with text_channel.typing():
                content = message.content
                author = message.author
                answer = self._get_ai_response(author, content)
                await message.author.send(answer)

            end = time.time()
            delta = end - start
            log_message = "Openai response took: "
            log_message += f" {format(delta, '.2f')} seconds."
            self.logger.debug(log_message)

    @commands.command()
    async def chat(self, ctx: commands.Context, *, message: str):
        """Bot chat command taking message as an argument.

        Adds message to chat log if there is any and passes entire log to Completion engine.
        First response from Completion engine is taken as an ouput and sent to user.

        Log is generated by separating output of the user and the Completion engine.
        Log is then saved as a deque list of maximum len of 20
        """
        async with ctx.typing():
            author = ctx.author
            answer = self._get_ai_response(author, message)
        await ctx.send(answer)

    @commands.command()
    async def log(self, ctx: commands.Context, query_id: int = 0):
        """Bot command that shows user's openai chat log.

        Chat log is sent to user as a string
        """
        user = ctx.author
        if ctx.author.id == self.config.bot_owner_id:
            print(self.chats)
            if query_id not in self.chats:
                return await ctx.send(f"{query_id} not in chat logs.")
            user = self.bot.get_user(query_id)
            if user is None:
                return await ctx.send("User not found.")
        chatlog = str(self._get_chatlog_from_user(user, self.bot.user.name)).strip()
        if len(chatlog) > 2000:
            await ctx.send("Chat log is too long to be sent to user.")
            with open("chatlog.txt", "w", encoding="utf-8") as temp_file:
                temp_file.write(chatlog)
                await ctx.send(file=discord.File("chatlog.txt"))
                os.remove("chatlog.txt")
            return
        chatlog = f"```{chatlog}```"
        await ctx.send(chatlog)

    @commands.command()
    async def log_clear(self, ctx: commands.Context):
        """Bot command that clears user's openai chat log.

        Chat log is reinitialized as a new deque list of maximum len of 20
        """
        chatlog = self._get_chatlog_from_user(ctx.author, self.bot.user.name)
        chatlog.clear()
        await ctx.send("Chat log cleared.")
